import Head from 'next/head'
import axios from 'axios'

import Header from '../components/sections/header'
import ProductList from '../components/sections/productlist'
import ProductFiltering from '../components/sections/productfiltering'

import { unique } from '../utils/unique'
import { Data, Products } from './api/products'

import styles from '../styles/Home.module.css'

type HomePageProps = {
  products: Products
  categories: ProductCategories
}

export default function Home({ products, categories }: HomePageProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
        <ProductFiltering categories={categories} />
        <ProductList products={products} />
      </main>
    </>
  )
}

export async function getServerSideProps() {
  const {
    data: { products },
  } = await axios.get<Data>('http://localhost:3000/api/products')
  const categories = unique(products.map((product) => product.category))

  return {
    props: {
      products,
      categories,
    },
  }
}
